# Copyright 2016 Jeffrey Kegler
# This file is part of Marpa::R3.  Marpa::R3 is free software: you can
# redistribute it and/or modify it under the terms of the GNU Lesser
# General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
#
# Marpa::R3 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser
# General Public License along with Marpa::R3.  If not, see
# http://www.gnu.org/licenses/.

=head1 NAME

Marpa::R3::Changes - Differences between Marpa::R2 and Marpa::R3

=head1 About this document

This document describes the incompatible
differences between Marpa::R2
and Marpa::R3.
(Differences that do not give rise to incompatibility
are outside of its scope.)
It is intended for readers already familiar with Marpa::R2,
who are writing new applications for Marpa::R3,
and for readers migrating Marpa::XS applications
and tools to Marpa::R3.

=head1 Changes

=head2 The Stuifzand interface (PSIF) has been removed

The Stuifzand interface (PSIF), and its documentation,
have been removed.
Important in the development of Marpa,
it now has little or now usage.

=head2 The Thin interface (THIF) is deprecated

The THIF is subject to major change, or outright removal,
without further notice.

=head2 The NAIF is deprecated

The NAIF is an older interface using hashes of named
variables, instead of a DSL.
It is now severely deprecated.
Expect it to be broken or removed shortly.

=head2 LATM is now the default

=head2 [name, values] is now the default action

=head2 Unicode now works in the SLIF DSL

=head2 Changes in names of location methods

The specific names changes of methods that deal with
G1 and input locations are given below.
The general idea is to make sure that
all methods that use G1 locations,
lengths, ranges or spans,
whether as arguments or as return values,
will have C<g1> as part of their name.

=head2 New method g1_input_span

=head2 Context::location is now Context::g1_range

=head2 New context variable, Context::g1_span

=head2 $slr->current_g1_location() is now $slr->g1_pos()

=head2 Deprecated named arguments of Scanless grammar elimated

The C<actions>, C<action_object>, C<default_action>
and C<default_empty_action>
named arguments no longer exist.

=head2 Marpa::R2::Scanless::R methods removed in Marpa::R3

The
Marpa::R2::Scanless::R::pause_lexeme method,
discouraged in Marpa::R2,
has been eliminated in Marpa::R3.

=head1 Copyright and License

=for Marpa::R3::Display
ignore: 1

  Copyright 2016 Jeffrey Kegler
  This file is part of Marpa::R3.  Marpa::R3 is free software: you can
  redistribute it and/or modify it under the terms of the GNU Lesser
  General Public License as published by the Free Software Foundation,
  either version 3 of the License, or (at your option) any later version.

  Marpa::R3 is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser
  General Public License along with Marpa::R3.  If not, see
  http://www.gnu.org/licenses/.

=for Marpa::R3::Display::End

=cut

