# Marpa::R3 is Copyright (C) 2017, Jeffrey Kegler.
#
# This module is free software; you can redistribute it and/or modify it
# under the same terms as Perl 5.10.1. For more details, see the full text
# of the licenses in the directory LICENSES.
#
# This program is distributed in the hope that it will be
# useful, but it is provided "as is" and without any express
# or implied warranties. For details, see the full text of
# of the licenses in the directory LICENSES.

=head1 NAME

Marpa::R3::Changes - Differences between Marpa::R2 and Marpa::R3

=head1 About this document

This document describes the incompatible
differences between Marpa::R2
and Marpa::R3.
(Differences that do not give rise to incompatibility
are outside of its scope.)
It is intended for readers already familiar with Marpa::R2,
who are writing new applications for Marpa::R3,
and for readers migrating Marpa::XS applications
and tools to Marpa::R3.

=head1 Changes

=head2 Events

In Marpa::R3, events have been changed from an event-driven
mechanism to a callback mechanism.
A new C<events_handlers> named argument has been added to
C<< Marpa::R3::Scanless::R::new() >>.
The
C<< $slr->events() >> method has been
removed.

=head2 New valuer object

There is a new valuer object,
with its own L<new
POD document|Marpa::R3::Scanless::V.pod>.

=head2 Marpa strings must be UTF-8

Marpa expects all strings passed to it to be valid UTF-8.
(Note that all ASCII-7 string are valid UTF-8).

=head2 "Eager" lexemes added

See L<Marpa::R3::Scanless::DSL/"eager">.

=head2 Problems with kernel Earley items in progress reports fixed

Progress reports had been misreporting some
Earley items.  The misreported items
were certain kernel Earley items
instances containing one
or more proper nullables.
By kernel Earley item, I mean an Earley item
where the dot is in the middle -- not at the beginning
and and not at the end.
In other words, kernel Earley items are items which
are not predictions, and which are not
completions.

This bug is actually quite obscure --
almost all interest in progress reports is in
completed Earley items, which were not affected.
So obscure, in fact, was this bug that
it went unnoticed in use.
It surfaced only when I reread the
code and realized that some corner cases were
not being dealt with correctly.
This bugs is now fixed.

=head2 Semantics moved from recognizer to grammar

In Marpa::R2, the semantics was not finally settled
until the C<< $recce->value() >> call.
In Marpa::R3, semantics will be fully settled in the grammar.

=head2 Recognizer value() method changed

The recognizer value() has changed.
Most notably, it
now throws a fatal error if
the parse is ambiguous -- this is
what most applications want.
Details are in L<its
documentation|Marpa::R3::Scanless::R/"value()">.

For dealing
with ambiguous parses, and other
advanced techniques,
there is a L<new
value object|Marpa::R3::Scanless::V>.

=head2 Recognizer named arguments

The C<exhaustion>,
C<ranking_method>,
C<rejection>,
C<semantics_package>,
and C<trace_actions>
recognizer named arguments
of Marpa::R2
have been removed.
In Marpa::R3,
they have become
are named arguments of grammar objects.

The C<max_parses>
recognizer named argument
of Marpa::R2
has been removed.
In Marpa::R3,
it has become a named argument of
the new valuator objects.

=head2 Actions that are Perl names must resolve to subroutines

It was a little noticed feature of Marpa::R2, that actions specified
as Perl names (like "My_Action::doit") could resolve to scalars.
In Marpa::R3 they must resolve to Perl subroutines.

=head2 The Stuifzand interface (PSIF) has been removed

The Stuifzand interface (PSIF), and its documentation,
have been removed.
Important in the development of Marpa,
it now has little or no usage.

=head2 The Thin interface (THIF) has been removed.

The THIF was a "thin" Perl interface.
It has been removed.

=head2 The NAIF has been removed

The NAIF was an older interface using hashes of named
variables, instead of a DSL.
It has been removed.

=head2 LATM is now the default

=head2 [name, values] is now the default action

=head2 Unicode now works in the SLIF DSL

=head2 Context::location is now Context::g1_range

=head2 New context variable, Context::g1_span

=head2 Marpa::R2::Scanless::G named arguments removed in Marpa::R3

The C<actions>, C<action_object>, C<default_action>
and C<default_empty_action>
named arguments
of Marpa::R2::Scanless::G named arguments
have been
removed in Marpa::R3.

=head2 Marpa::R3::Scanless::G accessors completely different

The grammar accessors changed between Marpa::R2
and Marpa::R3.
The changes are so massive that
any summary of the changes
to the SLG accessors
would be essentially be a repetition of
L<their
documentation|Marpa::R3::Scanless::G/"Accessors">.

=head2 Marpa::R2::Scanless::R methods changed in Marpa::R3

=head3 Multiple C<< slr->read() >> calls allowed

The interface to
the C<< $recce->read() >> method has changed in major ways.
One important change is that
the C<< slr->read() >> method may now called multiple
times during a parse,
each time with a new string.
These strings will be called B<input blocks>.
The <input block> read by the I<n>'th 
call of the C<< slr->read() >> method during a parse
has block index I<n>.

This change makes the previous L0 positions no
longer adequately identify a location, 
which necessitates many changes.

The interface to 
C< $recce->lexeme_alternative() >>
has changed.
Some of its functionality is taken over
by the new
C< $recce->lexeme_alternative_literal() >>
method.

The arguments of
C< $recce->lexeme_complete() >>,
C< $recce->input_length() >>,
and
C< $recce->literal() >>
have changed,
in a way which is not compatible with Marpa::R2.
Their first parameter now is the block id.

The
C< $recce->g1_location_to_span() >> and
C< $recce->last_completed_span() >>
methods has been removed.

For historical reasons,
the methods dealing with input and G1 parse location in Marpa::R2
often had unhelpful or misleading names.
In Marpa::R3 an attempt is being made to name
methods dealing with G1 and input parse location consistently,
and to ensure that the
G1 variants
have C<g1> somewhere in their name.
Accordingly,
C<< $slr->substring() >> has been renamed
C<< $slr->g1_literal() >>.

The
C<Marpa::R2::Scanless::R::event()> method,
C<Marpa::R2::Scanless::R::last_completed_range()> method,
C<Marpa::R2::Scanless::R::pause_lexeme()> method,
and the
C<Marpa::R2::Scanless::R::range_to_string()> method,
discouraged in Marpa::R2,
have been eliminated in Marpa::R3.

The C<Marpa::R2::Scanless::R::lexeme_read()> method
has been removed.
Its function is provided by the new
C<Marpa::R2::Scanless::R::lexeme_read_block()>
and C<Marpa::R2::Scanless::R::lexeme_read_string()>
methods.
C<Marpa::R2::Scanless::R::lexeme_read()> may reappear
in a non-backward-compatible form.

The C<Marpa::R2::Scanless::R::ambiguity_metric()> method
has been removed.
Its purpose is now served by the 
C<Marpa::R2::Scanless::V::ambiguity_level()> method.

The C<Marpa::R2::Scanless::R::ambiguous()> method
has been removed.
Its purpose is now served by the 
C<Marpa::R2::Scanless::V::ambiguous()> method.

The C<Marpa::R2::Scanless::R::current_g1_location()> method
has been removed.
Its purpose is now served by the 
C<Marpa::R2::Scanless::V::block_progress()> method.

The C<Marpa::R2::Scanless::R::pause_span()> method
has been removed.
Event location information is now available
as arguments to the
event handlers.

=head2 Marpa::R2::Scanless::R::line_column() changed

The interface to
C<Marpa::R2::Scanless::R::line_column()> has changed
to allow multi-block input.

=head2 Marpa::R2::Scanless::R::literal() changed

The interface to
C<Marpa::R2::Scanless::R::literal()> has changed
to allow multi-block input.

=head2 Marpa::R2::Scanless::R::progress() changed

C<Marpa::R2::Scanless::R::progress()> reported
the dot position of completions as -1.
In Marpa::R3,
C<< $slr->progress() >> reports
the dot position of completions as a non-negative integer,
consistent with other dot positions.
As a reminder, the dot position of a completed production is always
the same as its RHS length.

=head2 The per-parse constructor has been elminated

In Marpa::R2, if the semantics package has a C<new()>
method, that method was used as the constructor of
the per-parse object.
In Marpa::R3, there is no per-parse constructor.

=head2 The per-parse argument never affects the semantics package

As of Marpa::R3, the per-parse argument has no effect on
the semantics package.
In Marpa::R2, if the c<semantics_package> named argument was
not used and the per-parse argument was blessed,
then the package into which the per-parse argument was blessed
became the semantics package.

=head2 The semantic closure now always receives exactly 2 arguments

Under Marpa::R2, the semantic closure received a varying number
of arguments, depending on circumstances.
Under Marpa::R3, the semantic closure always receives exactly 
2 arguments.
The first argument is the per-parse object.
The second argument is a reference to an array containing
the values of the child nodes, in lexical order.
If there were no child nodes visible to the semantics,
then the second argument is an empty array.

=head1 COPYRIGHT AND LICENSE

=for Marpa::R3::Display
ignore: 1

  Marpa::R3 is Copyright (C) 2017, Jeffrey Kegler.

  This module is free software; you can redistribute it and/or modify it
  under the same terms as Perl 5.10.1. For more details, see the full text
  of the licenses in the directory LICENSES.

  This program is distributed in the hope that it will be
  useful, but without any warranty; without even the implied
  warranty of merchantability or fitness for a particular purpose.

=for Marpa::R3::Display::End

=cut

# vim: expandtab shiftwidth=4:
