# Marpa::R3 is Copyright (C) 2018, Jeffrey Kegler.
#
# This module is free software; you can redistribute it and/or modify it
# under the same terms as Perl 5.10.1. For more details, see the full text
# of the licenses in the directory LICENSES.
#
# This program is distributed in the hope that it will be
# useful, but it is provided "as is" and without any express
# or implied warranties. For details, see the full text of
# of the licenses in the directory LICENSES.

=head1 NAME

Marpa::R3::Support - Support, and how to report bugs

=head1 Description

Marpa::R3 is free software.
There is no warranty.

=head1 Mailing list

There is a Google Groups mailing list dedicated to Marpa at
L<https://groups.google.com/forum/?fromgroups#!forum/marpa-parser>.

=head1 Bugs

Please report any bugs or feature requests to
C<bug-marpa-xs at rt.cpan.org>, or through the web interface at
L<http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Marpa::R3>.
I will be notified, and then you'll automatically be notified of progress on
your bug as I make changes.

=head1 Other resources

You can find documentation for this module with the perldoc command.

=for Marpa::R3::Display
ignore: 1

    perldoc Marpa::R3

=for Marpa::R3::Display::End

You can also look for information at:

=over 4

=item * RT: CPAN's request tracker

L<http://rt.cpan.org/NoAuth/Bugs.html?Dist=Marpa-R2>

=item * Search CPAN

L<http://search.cpan.org/dist/Marpa-R2>

=back


=head1 COPYRIGHT AND LICENSE

=for Marpa::R3::Display
ignore: 1

  Marpa::R3 is Copyright (C) 2018, Jeffrey Kegler.

  This module is free software; you can redistribute it and/or modify it
  under the same terms as Perl 5.10.1. For more details, see the full text
  of the licenses in the directory LICENSES.

  This program is distributed in the hope that it will be
  useful, but without any warranty; without even the implied
  warranty of merchantability or fitness for a particular purpose.

=for Marpa::R3::Display::End

=cut

# vim: expandtab shiftwidth=4:
